-- An application's environments (SPEC §3.2b), where main declared them in `environments.yaml`: a
-- stage or production project of the application, its name, the branches it follows and its place
-- in the order they were declared in. Its tier is its project's kind there, by the key: it goes
-- with its project's row, and a move to another place records it anew.
CREATE UNIQUE INDEX hq_app_project_placement ON hq_app_project (project_id, app_id, kind);

CREATE TABLE hq_environment (
  project_id text PRIMARY KEY,
  app_id uuid NOT NULL,
  tier text NOT NULL CHECK (tier IN ('stage', 'production')),
  name text NOT NULL CHECK (name ~ '^[a-z][a-z0-9-]*$'),
  sources text[] NOT NULL CHECK (
    (tier = 'production' AND sources = '{release}')
    OR (tier = 'stage' AND cardinality(sources) > 0 AND NOT ('release' = ANY (sources)))
  ),
  declared_seq bigint GENERATED BY DEFAULT AS IDENTITY,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (app_id, name),
  FOREIGN KEY (project_id, app_id, tier) REFERENCES hq_app_project (project_id, app_id, kind)
    ON DELETE CASCADE
);

-- Every stage and production attached before: named after its tier, numbered within its
-- application in the order it was attached.
INSERT INTO hq_environment (project_id, app_id, tier, name, sources, created_by)
SELECT project_id, app_id, kind,
       CASE WHEN n = 1 THEN kind ELSE kind || '-' || n END,
       CASE WHEN kind = 'production' THEN '{release}'::text[] ELSE '{main}'::text[] END,
       created_by
FROM (
  SELECT project_id, app_id, kind, created_by, seq,
         row_number() OVER (PARTITION BY app_id, kind ORDER BY seq) AS n
  FROM hq_app_project WHERE kind IN ('stage', 'production')
) attached
ORDER BY seq;
