/**
 * The Gitea recipe, as the "create Gitea" button imports it — the services
 * half of `zeropsio/recipe-gitea`'s `zerops-project-import.yaml`, fetched
 * 2026-09-05.
 *
 * Two deliberate departures from the published file, both measured:
 *
 * 1. **The `project:` block is gone.** `POST /project/{id}/service-stack/import`
 *    rejects one outright (`projectImportProjectIncluded`), because mate
 *    creates the project itself — it has to, so it can tag it.
 * 2. **`GITEA_DOMAIN` takes the project's real region.** The published recipe
 *    hardcodes `app-prg1.zerops.app`, and that host does not resolve. A live
 *    import on 2026-09-05 served on `web-926-3000.prg1.zerops.app` while Gitea
 *    reported its own root URL as `web-926-3000.app-prg1.zerops.app`, which
 *    fails to resolve at all. Gitea derives `ROOT_URL` and `SSH_DOMAIN` from
 *    this value, so left alone every clone URL and web link it emits points
 *    nowhere.
 *
 * The `#zeropsPreprocessor=on` header is load-bearing and survives the strip:
 * `DB_PASSWORD` is generated by the platform's import preprocessor, and
 * `${zeropsSubdomainHost}` is resolved by it too.
 *
 * @module giteaRecipe
 */

/** Replaced with the project's region before import. */
const REGION_PLACEHOLDER = "__REGION__";

const GITEA_SERVICES_TEMPLATE =
  "#zeropsPreprocessor=on\nservices:\n  - hostname: db\n    type: postgresql:ha@18\n    profile: oltp-staging\n    priority: 10\n\n  - hostname: volume\n    type: local-storage@1\n    priority: 10\n\n  - hostname: web\n    type: ubuntu@26.04\n    vault:\n      DB_PASSWORD:\n        value: <@generateRandomString(<32>)>\n        sensitive: true\n      GITEA_DOMAIN: web-${zeropsSubdomainHost}-3000.__REGION__.zerops.app\n    maxContainers: 1\n    verticalAutoscaling:\n      minRam: 0.25\n    buildFromGit: https://github.com/zeropsio/recipe-gitea\n    enableSubdomainAccess: true";

/**
 * The import body for a Gitea project in `region` — the value
 * `zeropsRegionFromPublicZone` reads off the freshly created project.
 */
export function buildGiteaImportYaml(region: string): string {
  return GITEA_SERVICES_TEMPLATE.split(REGION_PLACEHOLDER).join(region);
}

const GITEA_RUNNER_TEMPLATE =
  "services:\n  - hostname: runner\n    type: ubuntu@26.04\n    vault:\n      RUNNER_REGISTRATION_TOKEN:\n        value: <generated-token>\n        sensitive: true\n    minContainers: 3\n    verticalAutoscaling:\n      minRam: 0.5\n    buildFromGit: https://github.com/zeropsio/recipe-gitea";

/** The token placeholder the published runner recipe ships with. */
const RUNNER_TOKEN_PLACEHOLDER = "<generated-token>";

/**
 * The CI-runner addon, with a registration token read out of the running
 * Gitea. A wrong token is not fatal and needs no re-import — the containers
 * restart until a valid one lands in `RUNNER_REGISTRATION_TOKEN`.
 */
export function buildGiteaRunnerImportYaml(registrationToken: string): string {
  return GITEA_RUNNER_TEMPLATE.split(RUNNER_TOKEN_PLACEHOLDER).join(registrationToken);
}
