export {
  DEFAULT_ZEROPS_API_BASE,
  ZeropsApiClient,
  ZeropsApiError,
  buildZeropsContainerUrl,
  isZcpService,
  zeropsClientsFromUser,
  zeropsRegionFromPublicZone,
  type ListProjectsOptions,
  type ZeropsApiClientOptions,
  type ZeropsApiErrorKind,
  type ZeropsClientMembership,
  type ZeropsLoginResponse,
  type ZeropsLocation,
  type ZeropsOrganization,
  type ZeropsOrganizationMember,
  type ZeropsProject,
  type ZeropsRegistrationResponse,
  type ZeropsService,
  type ZeropsServicePort,
  type ZeropsAutoscaling,
  type ZeropsAutoscalingResource,
  type ZeropsCurrentStat,
  type ZeropsStatHistoryItem,
  type ZeropsStatHistoryWindow,
  type ZeropsStatPair,
  type ZeropsUser,
} from "./api.ts";

export {
  canCreateProjectsInOrganization,
  resolveActiveZeropsOrganization,
  zeropsOrganizationRoleLabel,
  type ZeropsOrganizationSelectionInput,
} from "./accountScope.ts";

export {
  ZEROPS_SELECTION_STORAGE_KEY,
  ZEROPS_SESSION_STORAGE_KEY,
  clearZeropsSelection,
  clearZeropsSession,
  loadZeropsSelection,
  loadZeropsSession,
  isUsableZeropsSession,
  isZeropsSession,
  parseZeropsSession,
  requiresZeropsTwoFactor,
  saveZeropsSelection,
  saveZeropsSession,
  type ZeropsSelection,
  type ZeropsSession,
  type ZeropsStorageAdapter,
} from "./session.ts";

export {
  ZEROPS_CAPTCHA_ERROR_CODE,
  buildZeropsRegistrationBody,
  isZeropsCaptchaRejection,
  type ZeropsRegistrationBody,
  type ZeropsRegistrationInput,
} from "./registration.ts";

export {
  VSCODE_PASSWORD_LENGTH,
  ZEROPS_AGENT_TYPE_CANONICAL_ORDER,
  buildCreateProjectBody,
  buildDevelopmentContainerImportBody,
  buildZcpServiceImportYaml,
  generateVscodePassword,
  nextZcpServiceName,
  type CreateProjectBody,
  type DevelopmentContainerImportBody,
  type RandomBytes,
  type ZeropsAgentType,
} from "./newProject.ts";
export {
  MATE_MARKER_TAG,
  MATE_TAG_NAMESPACE,
  ZEROPS_GROUP_ID_LENGTH,
  deriveZeropsGroups,
  formatGroupTag,
  formatRoleTag,
  generateZeropsGroupId,
  readZeropsGroupTags,
  withZeropsBotTag,
  ZEROPS_BOT_NAME_MAX_LENGTH,
  withZeropsGroupTags,
  withZeropsMateTag,
  type DeriveZeropsGroupsOptions,
  type ZeropsEnvironmentRole,
  type ZeropsGroup,
  type ZeropsGroupEnvironment,
  type ZeropsGroupTags,
  type ZeropsGroupTree,
} from "./groups.ts";
export {
  ENVIRONMENTS_DOCUMENT_PATH,
  hasProjectBlock,
  importReadyTier,
  RECIPE_TIER_PATHS,
  recipeProjectImportYaml,
  recipeServicesYaml,
  type ImportReadyTier,
  type RecipeServiceSource,
  type RecipeTier,
} from "./recipeTier.ts";
export { agentsFromOAuthFlags, unionAgents } from "./agentSelection.ts";
export {
  ZEROPS_CREATION_HANDOFF_STORAGE_KEY,
  creationHandoffPrompt,
  parseCreationHandoffs,
  readCreationHandoff,
  creationJobSendable,
  creationJobToStart,
  withCreationHandoff,
  withCreationHandoffPromoted,
  withoutCreationHandoff,
  type ZeropsCreationHandoff,
  type ZeropsCreationHandoffs,
  type ZeropsCreationSource,
} from "./creationHandoff.ts";
export {
  derivePublicRouteOffers,
  derivePublicRoutes,
  type ZeropsPublicRoute,
  type ZeropsRouteOffer,
} from "./publicRoutes.ts";
export {
  summarizeEnvironmentServices,
  type ZeropsEnvironmentServices,
} from "./environmentSummary.ts";
export { assignCandidateMateTints, assignMateTints, preferredMateTint } from "./mateTints.ts";
export {
  selectAutoConnectTargets,
  ZEROPS_AUTO_CONNECT_LIMIT,
  type AutoConnectCandidate,
  type AutoConnectTarget,
} from "./autoConnect.ts";
export {
  deriveGiteaState,
  formatToolTag,
  GITEA_ADMIN_PASSWORD_ENV_KEY,
  GITEA_ADMIN_TOKEN_ENV_KEY,
  GITEA_ADMIN_USER_COMMAND,
  GITEA_BROKER_SERVICE,
  GITEA_BROKER_TOKEN_NAME,
  GITEA_ADMIN_USER_ENV_KEY,
  GITEA_HTTP_PORT,
  planGiteaProjectSetup,
  partitionZeropsToolProjects,
  readZeropsToolKind,
  type ZeropsGiteaPhase,
  type ZeropsGiteaSetupAction,
  type ZeropsGiteaSetupInput,
  type ZeropsGiteaProbe,
  type ZeropsGiteaSetupStep,
  type ZeropsGiteaState,
  type ZeropsGiteaStepState,
  type ZeropsToolKind,
  type ZeropsToolProject,
} from "./tools.ts";
export {
  buildGiteaImportYaml,
  GITEA_IMPORT_PLACEHOLDERS,
  GITEA_MATE_REPOSITORY,
  type GiteaImportInput,
} from "./giteaRecipe.ts";
export {
  resolvePrimaryConversation,
  type ZeropsConversationCandidate,
  type ZeropsPrimaryConversation,
  type ZeropsPrimaryConversationReason,
} from "./primaryConversation.ts";
export {
  agentOwnershipNeedsAttention,
  agentOwnershipNotice,
  resolveAgentOwnership,
  type ZeropsAgentAuthorizer,
  type ZeropsAgentOwnership,
  type ZeropsAgentOwnershipInput,
} from "./agentOwnership.ts";
export {
  defaultAgentForRole,
  environmentCreationStepLabel,
  planEnvironmentCreation,
  type EnvironmentCreationInput,
  type EnvironmentRecipeChoice,
  type EnvironmentCreationPlan,
  type EnvironmentCreationStep,
} from "./createEnvironment.ts";
export {
  ENVIRONMENT_SERVICE_POLL_INTERVAL_MS,
  ENVIRONMENT_SERVICE_WAIT_CAP_MS,
  runEnvironmentCreation,
  type EnvironmentCreationOutcome,
  type EnvironmentCreationPlatform,
  type EnvironmentCreationStepProgress,
  type EnvironmentCreationStepState,
  type GiteaCredentialOutcome,
  type RunEnvironmentCreationInput,
} from "./runEnvironmentCreation.ts";
export {
  buildZeropsGroupTree,
  type BuildZeropsGroupTreeOptions,
  type ZeropsGroupTreeEnvironment,
  type ZeropsGroupTreeGroup,
  type ZeropsGroupTreeTool,
  type ZeropsGroupTreeView,
  type ZeropsProjectCarrier,
} from "./groupTree.ts";
export { compareZeropsHostnames, rankZeropsCandidateForListing } from "./listingOrder.ts";
export {
  hasMate,
  hasMateContainer,
  mateEnvironmentsEmptyReason,
  selectMateEnvironments,
} from "./mateEnvironments.ts";
export { botDisplayName, generateBotName, hasBotName, ZEROPS_BOT_NAME_POOL } from "./bots.ts";
export {
  GITEA_MATE_TOKEN_SCOPES,
  GITEA_TOKEN_ENV_KEY,
  GITEA_URL_ENV_KEY,
  MATE_BROKER_URL_ENV_KEY,
  planGiteaCredential,
  planGiteaCredentialReconcile,
  planGiteaCredentialRequest,
  type GiteaCredentialReconcilePlan,
  type GiteaEndpoints,
  type MateGiteaAccess,
  type ZeropsGiteaCredentialInput,
  type ZeropsGiteaCredentialPlan,
  type ZeropsGiteaCredentialRequestInput,
} from "./giteaCredential.ts";
export {
  deriveGroupSlug,
  formatZeropsRegistryTags,
  GROUP_SLUG_MAX_LENGTH,
  GROUP_SLUG_PATTERN,
  parseZeropsRegistry,
  projectTagWriteBody,
  toRoleRegistry,
  type ZeropsRegistry,
  type ZeropsRegistryGroup,
  type ZeropsRegistryProject,
} from "./groupRegistry.ts";
export {
  planProjectIsolation,
  projectIsolationStepLabel,
  PROJECT_ENV_ISOLATION_KEY,
  PROJECT_ENV_ISOLATION_SERVICE,
  ZCP_API_KEY_ENV_KEY,
  type ProjectEnvEntry,
  type ProjectIsolationInput,
  type ProjectIsolationService,
  type ProjectIsolationStep,
} from "./projectIsolation.ts";
export {
  buildGroupGrants,
  findAccountMateTokens,
  findMateIntegrationToken,
  MATE_SELF_PROJECT_ROLE,
  planAccountGroupReach,
  planGroupReach,
  type ZeropsGroupReachGroup,
  type ZeropsGroupReachWrite,
  type ZeropsIntegrationToken,
  type ZeropsProjectGrant,
  type ZeropsProjectRole,
  type ZeropsTokenDelegation,
} from "./groupReach.ts";
export {
  base64UrlEncode,
  buildGiteaAuthorizationRequest,
  createGiteaOAuthState,
  createGiteaPkcePair,
  findGiteaOAuthApplication,
  GITEA_OAUTH_APPLICATION_NAME,
  GITEA_OAUTH_CALLBACK_PATH,
  GITEA_PKCE_METHOD,
  giteaOAuthApplicationBody,
  giteaOAuthRedirectUri,
  giteaRefreshBody,
  giteaTokenExchangeBody,
  readGiteaCallback,
  readGiteaTokenAnswer,
  type GiteaAuthorizationRequest,
  type GiteaCallbackResult,
  type GiteaOAuthApplication,
  type GiteaPkcePair,
  type GiteaTokenAnswer,
  type Sha256,
} from "./giteaOAuth.ts";
export {
  base64Decode,
  base64Encode,
  createGiteaClient,
  GiteaApiError,
  type GiteaActionJob,
  type GiteaActionRun,
  type GiteaBranch,
  type GiteaClient,
  type GiteaClientOptions,
  type GiteaCommitStatus,
  type GiteaFile,
  type GiteaFileChange,
  type GiteaOAuthApplicationRecord,
  type GiteaOrganization,
  type GiteaPullRequest,
  type GiteaRepository,
  type GiteaRepositoryPermissions,
  type GiteaUser,
} from "./giteaClient.ts";
export {
  canWriteRegistry,
  onlyTheseCanAddAProject,
  planGroupMembership,
  planGroupRegistration,
  mateAwaitingRegistryLine,
  resolveAddProjectVerb,
  resolveGroupGitea,
  resolveMateRegistration,
  type GroupGiteaState,
  type GroupMembershipResult,
  type GroupRegistrationPlan,
  type GroupRegistrationResult,
  type GroupVerb,
  type MateRegistration,
} from "./groupCreation.ts";
