export {
  DEFAULT_ZEROPS_API_BASE,
  ZeropsApiClient,
  ZeropsApiError,
  zeropsClientsFromUser,
  type ListProjectsOptions,
  type ZeropsApiClientOptions,
  type ZeropsApiErrorKind,
  type ZeropsClientMembership,
  type ZeropsLoginResponse,
  type ZeropsLocation,
  type ZeropsOrganization,
  type ZeropsOrganizationMember,
  type ZeropsProject,
  type ZeropsRegistrationResponse,
  type ZeropsService,
  type ZeropsServicePort,
  type ZeropsAutoscaling,
  type ZeropsAutoscalingResource,
  type ZeropsCurrentStat,
  type ZeropsStatHistoryItem,
  type ZeropsStatHistoryWindow,
  type ZeropsStatPair,
  type ZeropsUser,
  type WriteAdmission,
} from "./api.ts";

export {
  buildZeropsContainerUrl,
  isZcpService,
  zeropsRegionFromPublicZone,
} from "./containerAddress.ts";

export {
  canCreateProjectsInOrganization,
  resolveActiveZeropsOrganization,
  zeropsOrganizationRoleLabel,
  type ZeropsOrganizationSelectionInput,
} from "./accountScope.ts";

export {
  ZEROPS_SELECTION_STORAGE_KEY,
  ZEROPS_SESSION_STORAGE_KEY,
  clearZeropsSelection,
  clearZeropsSession,
  loadZeropsSelection,
  loadZeropsSession,
  isUsableZeropsSession,
  isZeropsSession,
  parseZeropsSession,
  requiresZeropsTwoFactor,
  saveZeropsSelection,
  saveZeropsSession,
  type ZeropsSelection,
  type ZeropsSession,
  type ZeropsStorageAdapter,
} from "./session.ts";

export {
  ZEROPS_CAPTCHA_ERROR_CODE,
  buildZeropsRegistrationBody,
  isZeropsCaptchaRejection,
  type ZeropsRegistrationBody,
  type ZeropsRegistrationInput,
} from "./registration.ts";

export {
  VSCODE_PASSWORD_LENGTH,
  ZEROPS_AGENT_TYPE_CANONICAL_ORDER,
  buildCreateProjectBody,
  buildDevelopmentContainerImportBody,
  buildZcpServiceImportYaml,
  generateVscodePassword,
  nextZcpServiceName,
  type CreateProjectBody,
  type DevelopmentContainerImportBody,
  type RandomBytes,
  type ZeropsAgentType,
} from "./newProject.ts";
export {
  MATE_MARKER_TAG,
  MATE_TAG_NAMESPACE,
  ZEROPS_GROUP_ID_LENGTH,
  changedMateFace,
  deriveZeropsGroups,
  formatMateFace,
  generateZeropsGroupId,
  kindOfRole,
  readMateFace,
  readZeropsMembership,
  ZEROPS_BOT_NAME_MAX_LENGTH,
  withZeropsMateTag,
  type BirthPlacement,
  type DeriveZeropsGroupsOptions,
  type ZeropsEnvironmentRole,
  type ZeropsGroup,
  type ZeropsGroupEnvironment,
  type ZeropsGroupPendingMember,
  type ZeropsGroupTree,
  type ZeropsMembership,
  type ZeropsMateFace,
  type ZeropsMateFaceTag,
  type ZeropsPlacedBirth,
  type ZeropsProjectOrder,
} from "./groups.ts";
export {
  deployTargetTier,
  hasProjectBlock,
  RECIPE_TIER_PATHS,
  recipeProjectImportYaml,
  recipeServicesWithout,
  recipeServicesYaml,
  recipeTierRepositories,
  recipeTierServices,
  splitRecipeTier,
  type RecipeRuntime,
  type RecipeRuntimeRole,
  type RecipeRuntimes,
  type RecipeServiceRole,
  type RecipeTier,
  type RecipeTierService,
  type RecipeTierSplit,
} from "./recipeTier.ts";
export { recipeReach, type RecipeReach } from "./recipeReach.ts";
export { agentsFromOAuthFlags, unionAgents } from "./agentSelection.ts";
export {
  isGenericPlatformError,
  projectCreationOutcome,
  type ZeropsProjectCreation,
  type ZeropsProjectCreationOutcome,
} from "./projectCreation.ts";
export {
  derivePublicRouteOffers,
  derivePublicRoutes,
  type ZeropsPublicRoute,
  type ZeropsRouteOffer,
} from "./publicRoutes.ts";
export {
  summarizeEnvironmentServices,
  type ZeropsEnvironmentServices,
} from "./environmentSummary.ts";
export {
  assignCandidateMateTints,
  assignMateTints,
  mateShapeOf,
  newMateTint,
  preferredMateTint,
} from "./mateTints.ts";
export {
  selectAutoConnectTargets,
  ZEROPS_AUTO_CONNECT_LIMIT,
  type AutoConnectCandidate,
} from "./autoConnect.ts";
export {
  deriveGiteaState,
  GITEA_ADMIN_PASSWORD_ENV_KEY,
  GITEA_ADMIN_TOKEN_ENV_KEY,
  GITEA_ADMIN_USER_COMMAND,
  GITEA_BROKER_SERVICE,
  GITEA_ADMIN_USER_ENV_KEY,
  GITEA_HTTP_PORT,
  partitionZeropsToolProjects,
  readZeropsToolKind,
  type ZeropsGiteaPhase,
  type ZeropsGiteaProbe,
  type ZeropsGiteaSetupStep,
  type ZeropsGiteaState,
  type ZeropsGiteaStepState,
  type ZeropsToolKind,
  type ZeropsToolProject,
} from "./tools.ts";
export {
  resolvePrimaryConversation,
  type ZeropsConversationCandidate,
  type ZeropsPrimaryConversation,
  type ZeropsPrimaryConversationReason,
} from "@t3tools/shared/primaryConversation";
export {
  agentOwnershipNeedsAttention,
  agentOwnershipNotice,
  resolveAgentOwnership,
  type ZeropsAgentAuthorizer,
  type ZeropsAgentOwnership,
  type ZeropsAgentOwnershipInput,
} from "./agentOwnership.ts";
export {
  defaultAgentForRole,
  environmentCreationStepLabel,
  planEnvironmentCreation,
  type EnvironmentCreationInput,
  type EnvironmentRecipeChoice,
  type EnvironmentCreationPlan,
  type EnvironmentCreationStep,
} from "./createEnvironment.ts";
export {
  ENVIRONMENT_SERVICE_POLL_INTERVAL_MS,
  ENVIRONMENT_SERVICE_WAIT_CAP_MS,
  PROJECT_CREATE_POLL_INTERVAL_MS,
  PROJECT_CREATE_WAIT_CAP_MS,
  PRESS_STEP_ATTEMPTS,
  PRESS_STEP_RETRY_MS,
  resumableEnvironmentCreationStep,
  runEnvironmentCreation,
  type EnvironmentCreationOutcome,
  type EnvironmentCreationPlatform,
  type EnvironmentCreationStepProgress,
  type EnvironmentCreationStepState,
  type RunEnvironmentCreationInput,
  type ServiceDeployment,
} from "./runEnvironmentCreation.ts";
export {
  buildZeropsGroupTree,
  type BuildZeropsGroupTreeOptions,
  type ZeropsGroupTreeEnvironment,
  type ZeropsGroupTreeGroup,
  type ZeropsGroupTreeTool,
  type ZeropsGroupTreeView,
  type ZeropsProjectCarrier,
} from "./groupTree.ts";
export { compareZeropsHostnames, rankZeropsCandidateForListing } from "./listingOrder.ts";
export {
  hasMate,
  hasMateContainer,
  mateEnvironmentsEmptyReason,
  selectMateEnvironments,
} from "./mateEnvironments.ts";
export { botDisplayName, generateBotName, ZEROPS_BOT_NAME_POOL } from "./bots.ts";
export {
  type ZeropsRegistry,
  type ZeropsRegistryGroup,
  type ZeropsRegistryProject,
} from "./hq/registry.ts";
export {
  planProjectIsolation,
  projectIsolationStepLabel,
  PROJECT_ENV_ISOLATION_KEY,
  PROJECT_ENV_ISOLATION_SERVICE,
  ZCP_API_KEY_ENV_KEY,
  type ProjectEnvEntry,
  type ProjectIsolationInput,
  type ProjectIsolationService,
  type ProjectIsolationStep,
} from "./projectIsolation.ts";
export {
  buildGroupGrants,
  findHeldMateKey,
  mateAdminKeys,
  mateHardenableBy,
  mateNeedsHarden,
  findMateIntegrationToken,
  newestMateKey,
  MATE_SELF_PROJECT_ROLE,
  planAccountGroupReach,
  makeTokenWriteLock,
  planGroupReach,
  tokenWriteLockName,
  TOKEN_WRITE_HOLD_MS,
  writeTokenProjectsFresh,
  type TokenWriteHold,
  type TokenWriteLocks,
  type ZeropsGroupReachGroup,
  type ZeropsGroupReachWrite,
  type ZeropsIntegrationToken,
  type ZeropsProjectGrant,
  type ZeropsProjectRole,
  type ZeropsTokenDelegation,
} from "./groupReach.ts";
export {
  gitCheckoutHostnames,
  environmentForBranch,
  gitActionAllowed,
  gitBlock,
  gitCheckoutLine,
  gitTrouble,
  gitVerdict,
  mateChangeIn,
  pullRequestBlocked,
  pullRequestBlockedReason,
  type GitBlock,
  type GitBlockAction,
  type GitBlockActionKind,
  type GitBlockEvidence,
  type GitBlockState,
  type GitChangedFile,
  type GitCheckoutState,
  type GitChangeState,
  type GitVerdict,
  type PullRequestBlocked,
} from "./gitTab.ts";
export { linkedChanges, linksChange } from "./changeLinks.ts";
export {
  branchLabel,
  mateBotLogin,
  mateProjectOfBranch,
  mateProjectOfLogin,
} from "./mateIdentity.ts";
export { mateNextStep, type MateNextStep } from "./mateNextStep.ts";
export {
  compareForRelease,
  flowReleaseOf,
  isReleaseTag,
  releaseRunBy,
  nameStopByRelease,
  newestReleaseTag,
  readReleaseMessage,
  readSemver,
  releaseEntries,
  releaseGate,
  releaseInFlight,
  releaseInFlightReason,
  releaseMessage,
  RELEASE_CHECKING,
  releaseCandidate,
  releaseOffer,
  releaseStatusContext,
  releaseTagName,
  releaseVerdict,
  releaseWord,
  RELEASE_NOTHING_MERGED,
  RELEASE_NOTHING_NEW_ON_MAIN,
  rollbackTo,
  suggestReleaseTags,
  type ReleaseAttempt,
  type ReleaseComparison,
  type ReleaseEntry,
  type ReleaseGate,
  type ReleaseVerdict,
  type Semver,
  GROUP_REPOSITORY,
  releaseRow,
  shortCommit,
  type FlowRelease,
  type FlowReleaseRow,
} from "./release.ts";
export {
  appRecipeOf,
  deployWord,
  environmentRowInputsOf,
  groupStopsOf,
  releaseDeploys,
  statedVersionNames,
  versionsStated,
  type AppRecipe,
  type GroupEnvironmentRowInput,
  type GroupEnvironmentService,
  type GroupStopProject,
  type GroupStops,
  type ReleaseDeploys,
} from "./groupDeploys.ts";
export { agentNeedsSignIn, AGENT_SIGN_IN_MESSAGE } from "./agentSignIn.ts";
export {
  groupHistory,
  historyAge,
  historyLine,
  historyNote,
  releaseTagsByCommit,
  type HistoryEntry,
} from "./groupHistory.ts";
export {
  releaseCarried,
  releaseCarriedToggleLabel,
  releaseDescription,
  releasesCarried,
  type ReleaseDescription,
  type ReleaseServiceChange,
} from "./releaseCarried.ts";
export {
  compareReadKey,
  movedCommits,
  releaseReads,
  wholeProduction,
  type CompareRead,
  type CompareReads,
  type Moved,
  type MovedCommits,
} from "./releaseCompare.ts";
export {
  ADD_PRODUCTION_LABEL,
  groupFlow,
  MAIN_WITHOUT_PRODUCTION,
  pairPreviewRoute,
  PRODUCTION_ADDED_HERE,
  PRODUCTION_AFTER_FIRST_MERGE,
  PRODUCTION_DEPLOYING,
  PRODUCTION_NOT_SET_UP,
  PRODUCTION_SETTING_UP,
  STAGE_SETTING_UP,
  type GroupFlow,
  type GroupFlowComing,
  type GroupFlowInput,
  type GroupFlowMain,
  type GroupFlowMate,
  type GroupFlowPending,
  type GroupFlowProduction,
  type GroupFlowPullRequest,
  type GroupFlowStop,
  type GroupFlowStopInput,
  type GroupFlowStopState,
  type GroupNextStep,
  type GroupNextStepKind,
  type GroupNextStepTarget,
} from "./groupFlow.ts";
export {
  stageMarks,
  stageStandings,
  type ServiceChanges,
  type StageMark,
  type StageStandings,
  type StopChange,
} from "./stageMarks.ts";
export {
  changesNotLive,
  PROJECT_ALL_CLEAR,
  projectAttention,
  type ProjectAttentionItem,
  type ProjectAttentionKind,
} from "./projectAttention.ts";
export {
  changeAskLabel,
  changeAskPrompt,
  changeConversationCount,
  changeRemarks,
  type ChangeRemark,
} from "./changeConversation.ts";
export {
  REVIEW_LABEL,
  REVIEW_RELEASE_LABEL,
  changeReview,
  crewTaskReview,
  releaseReview,
  reviewAge,
  rollbackReview,
  type ChangeReviewInput,
  type CrewTaskReviewInput,
  type ReleaseOutcome,
  type ReleaseReviewInput,
  type ReviewClose,
  type ReviewFix,
  type ReviewFixProblem,
  type ReviewModel,
  type ReviewPress,
  type ReviewPrimary,
  type ReviewSecondary,
  type ReviewState,
  type ReviewTone,
  type ReviewVerdict,
  type RollbackReviewInput,
} from "./reviewVerdict.ts";
export {
  changeReadout,
  type ChangeReadout,
  type ChangeReadoutCommit,
  type ChangeReadoutFile,
} from "./changeReadout.ts";
export {
  changeFileParts,
  parseChangeDiff,
  type ChangeDiffFile,
  type ChangeDiffHunk,
  type ChangeDiffLine,
} from "./changeDiff.ts";
export {
  createGiteaClient,
  GiteaApiError,
  type GiteaBranch,
  type GiteaClient,
  type GiteaClientOptions,
  type GiteaCommit,
  type GiteaCommitDetail,
  type GiteaCommitFile,
  type GiteaCommitStatus,
  type GiteaOrganization,
  type GiteaRepository,
  type GiteaRepositoryPermissions,
  type GiteaTag,
} from "./giteaClient.ts";
export {
  flowChange,
  flowChanges,
  flowVerbKey,
  flowVerbLabel,
  isRecipeProposal,
  pullRequestLineWith,
  pullRequestsByMate,
  agentTurnNotes,
  changeLandedEvents,
  type ChangeLandedEvent,
  changeState,
  pullRequestMergeLine,
  pullRequestsFolded,
  releaseContentsSentence,
  releaseWaitingLabel,
  type ReleaseContentsSummary,
  releaseContentsCommits,
  releaseContentsSummary,
  sidebarChangeLabel,
  changeNamesRepository,
  type FlowPullRequest,
  type FlowPullRequestKind,
  type FlowVerb,
} from "./projectFlow.ts";
export {
  deployTokenMint,
  deployTokenName,
  environmentKeyed,
  type DeployTokenMint,
} from "./deployToken.ts";
export {
  gitOverview,
  gitRepositoryLine,
  type GitOverviewApp,
  type GitOverviewChange,
  type GitOverviewRepository,
} from "./gitOverview.ts";
export {
  changeOffers,
  heldOf,
  mayOffer,
  offerAsker,
  releasePermission,
  type OfferAsker,
  type OfferViewer,
} from "./offers.ts";
export {
  canWriteRegistry,
  onlyTheseCanAddAProject,
  FINISH_MATE_SETUP_VERB,
  finishMateSetupScope,
  finishMateSetupVerb,
  resolveAddProjectVerb,
  resolveGroupGitea,
  resolveMateRegistration,
  type GroupGiteaState,
  type GroupVerb,
  type MateRegistration,
} from "./groupCreation.ts";
export {
  halfMadeGroupEnvironments,
  type HalfMadeGroupEnvironment,
  environmentTierForRole,
  type GroupEnvironment,
  type GroupEnvironmentTier,
  missingEnvironmentRows,
  MISSING_ENVIRONMENT_LINE,
  type MissingEnvironmentRow,
} from "./groupEnvironments.ts";
export {
  deployedCommit,
  deployedVersion,
  deployTone,
  environmentNameUnderGroup,
  environmentRow,
  GROUP_BEING_SET_UP_LINE,
  type DeployedVersion,
  type EnvironmentRow,
  type EnvironmentServiceState,
  type GroupRowTone,
} from "./groupRows.ts";
export {
  parseVersionName,
  resolveCommit,
  sameCommit,
  SHORT_SHA_LENGTH,
  type ParsedVersionName,
} from "./versionName.ts";
