import type { OrchestrationLatestTurn, OrchestrationSession } from "@t3tools/contracts";
import { ThreadId, TurnId } from "@t3tools/contracts";
import type { AgentAwarenessPhase } from "./agentAwareness.ts";
import type { ThreadStatus, ThreadStatusInput, ThreadStatusToneId } from "./threadStatus.ts";

type ThreadStatusVector = {
  readonly name: string;
  readonly input: ThreadStatusInput;
  readonly expected: ThreadStatus;
  readonly expectedLabel: string | null;
  readonly expectedPulse: boolean;
  readonly expectedAwarenessPhase: Exclude<AgentAwarenessPhase, "stale"> | null;
  readonly expectedAwarenessLabel: string | null;
  readonly expectedAwarenessToneId: ThreadStatusToneId | null;
  readonly expectedWidgetTrailing: string | null;
};

const NOW = "2026-08-30T12:00:00.000Z";
const BEFORE = "2026-08-30T11:00:00.000Z";
const AFTER = "2026-08-30T13:00:00.000Z";

const runningSession = {
  threadId: ThreadId.make("thread-status-vector"),
  status: "running",
  providerName: "Codex",
  runtimeMode: "full-access",
  activeTurnId: TurnId.make("turn-status-vector"),
  lastError: null,
  updatedAt: NOW,
} satisfies OrchestrationSession;

const completedTurn = {
  turnId: TurnId.make("turn-status-vector"),
  state: "completed",
  requestedAt: BEFORE,
  startedAt: BEFORE,
  completedAt: NOW,
  assistantMessageId: null,
} satisfies OrchestrationLatestTurn;

const baseInput = {
  hasPendingApprovals: false,
  hasPendingUserInput: false,
  hasActionableProposedPlan: false,
  interactionMode: "default",
  latestTurn: null,
  session: null,
  backgroundLiveness: null,
} satisfies ThreadStatusInput;

export const threadStatusVectors: ReadonlyArray<ThreadStatusVector> = [
  {
    name: "approval outranks input and a running session",
    input: {
      ...baseInput,
      hasPendingApprovals: true,
      hasPendingUserInput: true,
      session: runningSession,
    },
    expected: { kind: "approval", toneId: "attention" },
    expectedLabel: "Approval",
    expectedPulse: false,
    expectedAwarenessPhase: "waiting_for_approval",
    expectedAwarenessLabel: "Approval",
    expectedAwarenessToneId: "attention",
    expectedWidgetTrailing: "Approval",
  },
  {
    name: "input outranks a running session",
    input: { ...baseInput, hasPendingUserInput: true, session: runningSession },
    expected: { kind: "input", toneId: "input" },
    expectedLabel: "Input",
    expectedPulse: false,
    expectedAwarenessPhase: "waiting_for_input",
    expectedAwarenessLabel: "Input",
    expectedAwarenessToneId: "input",
    expectedWidgetTrailing: "Input",
  },
  {
    name: "a running session is working",
    input: { ...baseInput, session: runningSession },
    expected: { kind: "working", toneId: "active" },
    expectedLabel: "Working",
    expectedPulse: true,
    expectedAwarenessPhase: "running",
    expectedAwarenessLabel: "Working",
    expectedAwarenessToneId: "active",
    expectedWidgetTrailing: "1 active",
  },
  {
    name: "a running latest turn is working even when the session is ready",
    input: {
      ...baseInput,
      latestTurn: { ...completedTurn, state: "running", completedAt: null },
      session: { ...runningSession, status: "ready", activeTurnId: null },
    },
    expected: { kind: "working", toneId: "active" },
    expectedLabel: "Working",
    expectedPulse: true,
    expectedAwarenessPhase: "running",
    expectedAwarenessLabel: "Working",
    expectedAwarenessToneId: "active",
    expectedWidgetTrailing: "1 active",
  },
  {
    name: "a starting session is connecting",
    input: { ...baseInput, session: { ...runningSession, status: "starting" } },
    expected: { kind: "connecting", toneId: "active" },
    expectedLabel: "Connecting",
    expectedPulse: true,
    expectedAwarenessPhase: "starting",
    expectedAwarenessLabel: "Connecting",
    expectedAwarenessToneId: "active",
    expectedWidgetTrailing: "1 active",
  },
  {
    name: "a session failure outranks stale working liveness",
    input: {
      ...baseInput,
      session: { ...runningSession, status: "error", activeTurnId: null, lastError: "boom" },
      backgroundLiveness: "working",
    },
    expected: { kind: "failed", toneId: "danger" },
    expectedLabel: "Failed",
    expectedPulse: false,
    expectedAwarenessPhase: "failed",
    expectedAwarenessLabel: "Failed",
    expectedAwarenessToneId: "danger",
    expectedWidgetTrailing: "Failed",
  },
  {
    name: "a latest-turn failure is visible with an idle session",
    input: {
      ...baseInput,
      latestTurn: { ...completedTurn, state: "error" },
      session: { ...runningSession, status: "idle", activeTurnId: null },
    },
    expected: { kind: "failed", toneId: "danger" },
    expectedLabel: "Failed",
    expectedPulse: false,
    expectedAwarenessPhase: "failed",
    expectedAwarenessLabel: "Failed",
    expectedAwarenessToneId: "danger",
    expectedWidgetTrailing: "Failed",
  },
  {
    name: "a live session outranks a ready plan",
    input: {
      ...baseInput,
      hasActionableProposedPlan: true,
      interactionMode: "plan",
      latestTurn: completedTurn,
      session: runningSession,
    },
    expected: { kind: "working", toneId: "active" },
    expectedLabel: "Working",
    expectedPulse: true,
    expectedAwarenessPhase: "running",
    expectedAwarenessLabel: "Working",
    expectedAwarenessToneId: "active",
    expectedWidgetTrailing: "1 active",
  },
  {
    name: "a ready plan outranks background working liveness",
    input: {
      ...baseInput,
      hasActionableProposedPlan: true,
      interactionMode: "plan",
      latestTurn: completedTurn,
      session: { ...runningSession, status: "ready", activeTurnId: null },
      backgroundLiveness: "working",
    },
    expected: { kind: "planReady", toneId: "plan" },
    expectedLabel: "Plan Ready",
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "a settled actionable plan is ready",
    input: {
      ...baseInput,
      hasActionableProposedPlan: true,
      interactionMode: "plan",
      latestTurn: completedTurn,
      session: { ...runningSession, status: "ready", activeTurnId: null },
    },
    expected: { kind: "planReady", toneId: "plan" },
    expectedLabel: "Plan Ready",
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "background working liveness is working",
    input: { ...baseInput, backgroundLiveness: "working" },
    expected: { kind: "working", toneId: "active" },
    expectedLabel: "Working",
    expectedPulse: true,
    expectedAwarenessPhase: null,
    expectedAwarenessLabel: null,
    expectedAwarenessToneId: null,
    expectedWidgetTrailing: null,
  },
  {
    name: "a completed turn with background working liveness stays completed for awareness",
    input: {
      ...baseInput,
      latestTurn: completedTurn,
      session: { ...runningSession, status: "ready", activeTurnId: null },
      backgroundLiveness: "working",
    },
    expected: { kind: "working", toneId: "active" },
    expectedLabel: "Working",
    expectedPulse: true,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "background monitoring liveness is monitoring",
    input: { ...baseInput, backgroundLiveness: "monitoring" },
    expected: { kind: "monitoring", toneId: "active" },
    expectedLabel: "Monitoring",
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "an unseen completion is done",
    input: { ...baseInput, latestTurn: completedTurn, lastVisitedAt: BEFORE },
    expected: { kind: "done", toneId: "success" },
    expectedLabel: "Done",
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "an unseen completion that also woke needs attention",
    input: {
      ...baseInput,
      latestTurn: completedTurn,
      lastVisitedAt: BEFORE,
      wokeAt: NOW,
    },
    expected: { kind: "woke", toneId: "attention" },
    expectedLabel: "Woke",
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "a completion without client-local visit state is idle",
    input: { ...baseInput, latestTurn: completedTurn },
    expected: { kind: "idle", toneId: "neutral" },
    expectedLabel: null,
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "a completion already visited is idle",
    input: { ...baseInput, latestTurn: completedTurn, lastVisitedAt: AFTER },
    expected: { kind: "idle", toneId: "neutral" },
    expectedLabel: null,
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "a wake newer than the last visit is woke",
    input: { ...baseInput, lastVisitedAt: BEFORE, wokeAt: NOW },
    expected: { kind: "woke", toneId: "attention" },
    expectedLabel: "Woke",
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "a wake with no client-local visit is woke",
    input: { ...baseInput, wokeAt: NOW },
    expected: { kind: "woke", toneId: "attention" },
    expectedLabel: "Woke",
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "an interrupted turn with a completion timestamp is idle but completed for awareness",
    input: { ...baseInput, latestTurn: { ...completedTurn, state: "interrupted" } },
    expected: { kind: "idle", toneId: "neutral" },
    expectedLabel: null,
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "a ready session with no materialized turn is idle but completed for awareness",
    input: {
      ...baseInput,
      session: { ...runningSession, status: "ready", activeTurnId: null },
    },
    expected: { kind: "idle", toneId: "neutral" },
    expectedLabel: null,
    expectedPulse: false,
    expectedAwarenessPhase: "completed",
    expectedAwarenessLabel: "Done",
    expectedAwarenessToneId: "success",
    expectedWidgetTrailing: "Done",
  },
  {
    name: "no session and no turn is idle with no awareness phase",
    input: baseInput,
    expected: { kind: "idle", toneId: "neutral" },
    expectedLabel: null,
    expectedPulse: false,
    expectedAwarenessPhase: null,
    expectedAwarenessLabel: null,
    expectedAwarenessToneId: null,
    expectedWidgetTrailing: null,
  },
];
