#!/usr/bin/env node

import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import * as NodeServices from "@effect/platform-node/NodeServices";
import {
  CSS_KIND,
  cssDeclarationFingerprint,
  formatReconcileReport,
  loadCompletedPhases,
  loadExceptionLedger,
  reconcileExceptions,
  type ExceptionFinding,
} from "@t3tools/oxlint-plugin-t3code/exceptions";
import * as Console from "effect/Console";
import * as Data from "effect/Data";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import * as PlatformError from "effect/PlatformError";
import { Command } from "effect/unstable/cli";
import * as NodeURL from "node:url";

const RULE_NAME = "no-infinite-motion";
const GENERATED_HEADER_PATTERN =
  /^\s*\/\*[\s\S]{0,240}?generated by [\s\S]*?do not edit manually\.[\s\S]*?\*\//iu;
const INFINITE_TOKEN_PATTERN = /(?:^|[^-_a-z0-9])infinite(?=$|[^-_a-z0-9])/iu;
const TARGET_PROPERTIES = new Set(["animation", "animation-name", "animation-iteration-count"]);
const EXCLUDED_DIRECTORIES = new Set(["dist", "node_modules"]);
const CSS_KEYWORDS = new Set([
  "alternate",
  "alternate-reverse",
  "backwards",
  "both",
  "ease",
  "ease-in",
  "ease-in-out",
  "ease-out",
  "forwards",
  "infinite",
  "initial",
  "inherit",
  "linear",
  "none",
  "normal",
  "paused",
  "revert",
  "reverse",
  "running",
  "step-end",
  "step-start",
  "unset",
]);
const DEFAULT_REPO_ROOT = NodeURL.fileURLToPath(new URL("..", import.meta.url));

interface CssDeclaration {
  readonly property: string;
  readonly value: string;
}

interface CssBlock {
  readonly header: string;
  readonly parent: CssBlock | undefined;
  readonly declarations: Array<CssDeclaration>;
  readonly children: Array<CssBlock>;
}

interface KeyframeStop {
  readonly position: number;
  readonly timing: string | undefined;
}

interface ParsedKeyframes {
  readonly stops: ReadonlyArray<KeyframeStop>;
}

interface AnimationUse {
  readonly name: string | undefined;
  readonly duration: number | undefined;
  readonly timing: string | undefined;
}

export interface CssMotionSource {
  readonly path: string;
  readonly source: string;
}

export interface CssMotionFinding extends ExceptionFinding {
  readonly detail: string;
}

export interface CssMotionCheckResult {
  readonly report: string;
  readonly problemCount: number;
  readonly exitCode: 0 | 1;
}

class CssMotionCheckError extends Data.TaggedClass("CssMotionCheckError")<{
  readonly operation: string;
  readonly cause: unknown;
}> {
  readonly name = "CssMotionCheckError";

  get message(): string {
    return `CSS motion check failed while ${this.operation}.`;
  }
}

const withoutComments = (text: string): string => text.replace(/\/\*[\s\S]*?\*\//gu, " ").trim();

const declarationFrom = (text: string): CssDeclaration | undefined => {
  const cleaned = withoutComments(text);
  const colonIndex = cleaned.indexOf(":");
  if (colonIndex <= 0) return undefined;
  const property = cleaned.slice(0, colonIndex).trim().toLowerCase();
  const value = cleaned.slice(colonIndex + 1).trim();
  return property.length > 0 && value.length > 0 ? { property, value } : undefined;
};

const parseCssBlocks = (source: string): CssBlock => {
  const root: CssBlock = {
    header: "<root>",
    parent: undefined,
    declarations: [],
    children: [],
  };
  const stack: Array<{ readonly block: CssBlock; segmentStart: number }> = [
    { block: root, segmentStart: 0 },
  ];
  let quote: '"' | "'" | undefined;
  let parentheses = 0;
  let brackets = 0;

  for (let index = 0; index < source.length; index++) {
    const character = source[index]!;
    const next = source[index + 1];
    if (quote !== undefined) {
      if (character === "\\") index++;
      else if (character === quote) quote = undefined;
      continue;
    }
    if (character === '"' || character === "'") {
      quote = character;
      continue;
    }
    if (character === "/" && next === "*") {
      const commentEnd = source.indexOf("*/", index + 2);
      index = commentEnd === -1 ? source.length : commentEnd + 1;
      continue;
    }
    if (character === "(") parentheses++;
    else if (character === ")") parentheses = Math.max(0, parentheses - 1);
    else if (character === "[") brackets++;
    else if (character === "]") brackets = Math.max(0, brackets - 1);
    if (parentheses > 0 || brackets > 0) continue;

    const frame = stack.at(-1)!;
    if (character === "{") {
      const block: CssBlock = {
        header: withoutComments(source.slice(frame.segmentStart, index)),
        parent: frame.block,
        declarations: [],
        children: [],
      };
      frame.block.children.push(block);
      stack.push({ block, segmentStart: index + 1 });
    } else if (character === ";") {
      const declaration = declarationFrom(source.slice(frame.segmentStart, index));
      if (declaration !== undefined) frame.block.declarations.push(declaration);
      frame.segmentStart = index + 1;
    } else if (character === "}" && stack.length > 1) {
      const declaration = declarationFrom(source.slice(frame.segmentStart, index));
      if (declaration !== undefined) frame.block.declarations.push(declaration);
      stack.pop();
      stack.at(-1)!.segmentStart = index + 1;
    }
  }

  return root;
};

const walkBlocks = (root: CssBlock): ReadonlyArray<CssBlock> => {
  const blocks: Array<CssBlock> = [];
  const visit = (block: CssBlock) => {
    blocks.push(block);
    for (const child of block.children) visit(child);
  };
  visit(root);
  return blocks;
};

const splitTopLevelCommas = (value: string): ReadonlyArray<string> => {
  const items: Array<string> = [];
  let start = 0;
  let quote: '"' | "'" | undefined;
  let parentheses = 0;
  let brackets = 0;

  for (let index = 0; index < value.length; index++) {
    const character = value[index]!;
    if (quote !== undefined) {
      if (character === "\\") index++;
      else if (character === quote) quote = undefined;
      continue;
    }
    if (character === '"' || character === "'") {
      quote = character;
      continue;
    }
    if (character === "(") parentheses++;
    else if (character === ")") parentheses = Math.max(0, parentheses - 1);
    else if (character === "[") brackets++;
    else if (character === "]") brackets = Math.max(0, brackets - 1);
    else if (character === "," && parentheses === 0 && brackets === 0) {
      items.push(value.slice(start, index).trim());
      start = index + 1;
    }
  }
  items.push(value.slice(start).trim());
  return items.filter((item) => item.length > 0);
};

const keyframePosition = (selector: string): number | undefined => {
  const normalized = selector.trim();
  if (/^from$/iu.test(normalized)) return 0;
  if (/^to$/iu.test(normalized)) return 100;
  const percentage = /^([+-]?(?:\d+(?:\.\d*)?|\.\d+))%$/u.exec(normalized);
  if (percentage === null) return undefined;
  const position = Number(percentage[1]);
  return position >= 0 && position <= 100 ? position : undefined;
};

const keyframesFrom = (blocks: ReadonlyArray<CssBlock>): ReadonlyMap<string, ParsedKeyframes> => {
  const keyframes = new Map<string, ParsedKeyframes>();
  for (const block of blocks) {
    const match = /^@(?:-[a-z]+-)?keyframes\s+([_a-zA-Z][-_a-zA-Z0-9]*)$/u.exec(block.header);
    if (match === null) continue;
    const authoredStops = block.children.flatMap((stop) => {
      const timing = stop.declarations
        .toReversed()
        .find((declaration) => declaration.property === "animation-timing-function")?.value;
      return splitTopLevelCommas(stop.header).flatMap((selector) => {
        const position = keyframePosition(selector);
        return position === undefined ? [] : [{ position, timing }];
      });
    });
    const positions = new Set(authoredStops.map((stop) => stop.position));
    const stops = [
      ...(positions.has(0) ? [] : [{ position: 0, timing: undefined }]),
      ...authoredStops,
      ...(positions.has(100) ? [] : [{ position: 100, timing: undefined }]),
    ].toSorted((left, right) => left.position - right.position);
    keyframes.set(match[1]!, { stops });
  }
  return keyframes;
};

const insideKeyframes = (block: CssBlock): boolean => {
  let current: CssBlock | undefined = block;
  while (current !== undefined) {
    if (/^@(?:-[a-z]+-)?keyframes\s+/u.test(current.header)) return true;
    current = current.parent;
  }
  return false;
};

const identifierTokens = (value: string): ReadonlyArray<string> =>
  [...value.matchAll(/[_a-zA-Z][-_a-zA-Z0-9]*/gu)].map((match) => match[0]);

const animationNameFrom = (
  value: string,
  keyframes: ReadonlyMap<string, ParsedKeyframes>,
): string | undefined => {
  const identifiers = identifierTokens(value);
  return (
    identifiers.find((identifier) => keyframes.has(identifier)) ??
    identifiers.find((identifier) => !CSS_KEYWORDS.has(identifier.toLowerCase()))
  );
};

const durationMilliseconds = (value: string): number | undefined => {
  const match = /(?:^|[\s,])(\d*\.?\d+)(ms|s)(?=$|[\s,])/u.exec(value);
  if (match === null) return undefined;
  const amount = Number(match[1]);
  return match[2] === "s" ? amount * 1000 : amount;
};

const timingIsCappedSteps = (value: string): boolean => {
  const match = /^steps\(\s*(\d+)(?:\s*,\s*[-a-z]+)?\s*\)$/iu.exec(value.trim());
  return match !== null && Number(match[1]) >= 1 && Number(match[1]) <= 8;
};

const shorthandTiming = (value: string): string | undefined =>
  /(?:^|\s)(steps\([^)]*\)|step-start|step-end|linear(?:\([^)]*\))?|ease(?:-in(?:-out)?|-out)?|cubic-bezier\([^)]*\))(?=$|\s)/iu.exec(
    value,
  )?.[1];

const declarationValue = (block: CssBlock, property: string): string | undefined =>
  block.declarations.toReversed().find((candidate) => candidate.property === property)?.value;

const listItem = (value: string | undefined, index: number): string | undefined => {
  if (value === undefined) return undefined;
  const items = splitTopLevelCommas(value);
  return items.length === 0 ? undefined : items[index % items.length];
};

const animationUsesFrom = (
  declaration: CssDeclaration,
  block: CssBlock,
  keyframes: ReadonlyMap<string, ParsedKeyframes>,
): ReadonlyArray<AnimationUse> => {
  const values = splitTopLevelCommas(declaration.value);
  const timings = declarationValue(block, "animation-timing-function");
  if (declaration.property === "animation" || declaration.property.startsWith("--animate-")) {
    return values.flatMap((value, index) => {
      if (!INFINITE_TOKEN_PATTERN.test(value)) return [];
      return [
        {
          name: animationNameFrom(value, keyframes),
          duration: durationMilliseconds(value),
          timing: shorthandTiming(value) ?? listItem(timings, index),
        },
      ];
    });
  }

  const names = declarationValue(block, "animation-name");
  const durations = declarationValue(block, "animation-duration");
  return values.flatMap((value, index) => {
    if (!INFINITE_TOKEN_PATTERN.test(value)) return [];
    const nameValue = declaration.property === "animation-name" ? value : listItem(names, index);
    return [
      {
        name: nameValue === undefined ? undefined : animationNameFrom(nameValue, keyframes),
        duration: durationMilliseconds(listItem(durations, index) ?? ""),
        timing: listItem(timings, index),
      },
    ];
  });
};

const firstUnsteppedInterval = (
  keyframes: ParsedKeyframes,
  declaredTiming: string | undefined,
): readonly [KeyframeStop, KeyframeStop] | undefined => {
  for (const [index, stop] of keyframes.stops.entries()) {
    const nextStop = keyframes.stops
      .slice(index + 1)
      .find((candidate) => candidate.position > stop.position);
    if (nextStop !== undefined && !timingIsCappedSteps(stop.timing ?? declaredTiming ?? "ease")) {
      return [stop, nextStop];
    }
  }
  return undefined;
};

const keyframePositionLabel = (stop: KeyframeStop): string => `${stop.position}%`;

const findingDetail = ({
  name,
  keyframes,
  duration,
  timing,
}: {
  readonly name: string | undefined;
  readonly keyframes: ParsedKeyframes | undefined;
  readonly duration: number | undefined;
  readonly timing: string | undefined;
}): string | undefined => {
  if (name === undefined) return "Could not resolve a keyframe name from the infinite animation.";
  if (keyframes === undefined) return `Animation "${name}" has no matching @keyframes block.`;
  const unsteppedInterval = firstUnsteppedInterval(keyframes, timing);
  if (unsteppedInterval !== undefined) {
    const [start, end] = unsteppedInterval;
    return `Animation "${name}" has an unstepped ${keyframePositionLabel(start)}→${keyframePositionLabel(end)} interval; every non-terminal stop must use steps(k) with k no greater than 8.`;
  }
  if (duration === undefined || duration < 1000) {
    return `Animation "${name}" must have a duration of at least 1s.`;
  }
  return undefined;
};

/** Scans one authored CSS source for continuous animation declarations. */
export const scanCssMotion = (path: string, source: string): ReadonlyArray<CssMotionFinding> => {
  if (GENERATED_HEADER_PATTERN.test(source.slice(0, 512))) return [];

  const blocks = walkBlocks(parseCssBlocks(source));
  const keyframes = keyframesFrom(blocks);
  const findings: Array<CssMotionFinding> = [];
  for (const block of blocks) {
    if (insideKeyframes(block)) continue;
    for (const declaration of block.declarations) {
      const isTarget =
        TARGET_PROPERTIES.has(declaration.property) ||
        declaration.property.startsWith("--animate-");
      if (!isTarget || !INFINITE_TOKEN_PATTERN.test(declaration.value)) continue;

      for (const animation of animationUsesFrom(declaration, block, keyframes)) {
        const resolvedKeyframes =
          animation.name === undefined ? undefined : keyframes.get(animation.name);
        const detail = findingDetail({ ...animation, keyframes: resolvedKeyframes });
        if (detail === undefined) continue;
        findings.push({
          path,
          kind: CSS_KIND,
          fingerprint: cssDeclarationFingerprint({
            selector: block.header,
            property: declaration.property,
            value: declaration.value,
          }),
          detail,
        });
      }
    }
  }
  return findings;
};

/** Reconciles scanner output against the CSS portion of the R6 exception ledger. */
export const checkCssMotion = Effect.fn("checkCssMotion")(function* ({
  directory,
  sources,
}: {
  readonly directory: string;
  readonly sources: ReadonlyArray<CssMotionSource>;
}) {
  const { ledger, completedPhases } = yield* Effect.try({
    try: () => ({
      ledger: loadExceptionLedger(RULE_NAME, directory),
      completedPhases: loadCompletedPhases(directory),
    }),
    catch: (cause) => new CssMotionCheckError({ operation: "loading the ledger", cause }),
  });
  const findings = sources.flatMap(({ path, source }) =>
    scanCssMotion(path, source).map((finding) => ({
      ...finding,
      ledgered: ledger.has(finding),
    })),
  );
  const result = reconcileExceptions({
    entries: ledger.entries,
    findings,
    completedPhases,
    scope: "css",
  });
  const problemCount =
    result.unlisted.length + result.dead.length + result.changed.length + result.expired.length;
  const details = findings
    .filter((finding) => !finding.ledgered)
    .map((finding) => `${finding.path}: ${finding.detail}`);
  const reconciliation = formatReconcileReport({ ruleName: RULE_NAME, result });
  return {
    report: [...details, reconciliation].join("\n"),
    problemCount,
    exitCode: problemCount > 0 ? 1 : 0,
  } satisfies CssMotionCheckResult;
});

const collectCssFiles = (
  root: string,
): Effect.Effect<
  ReadonlyArray<string>,
  PlatformError.PlatformError,
  FileSystem.FileSystem | Path.Path
> =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    if (!(yield* fs.exists(root))) return [];
    const entries = yield* fs.readDirectory(root);
    const files: Array<string> = [];
    for (const entry of entries) {
      if (EXCLUDED_DIRECTORIES.has(entry)) continue;
      const entryPath = path.join(root, entry);
      const stat = yield* fs.stat(entryPath);
      if (stat.type === "Directory") files.push(...(yield* collectCssFiles(entryPath)));
      else if (stat.type === "File" && path.extname(entry) === ".css") files.push(entryPath);
    }
    return files;
  });

const runCssMotionCheck = Effect.fn("runCssMotionCheck")(function* () {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const roots = [
    path.join(DEFAULT_REPO_ROOT, "apps/web/src"),
    path.join(DEFAULT_REPO_ROOT, "apps/mobile"),
  ];
  const files = (yield* Effect.all(roots.map(collectCssFiles))).flat().toSorted();
  const sources = yield* Effect.all(
    files.map((file) =>
      fs.readFileString(file).pipe(
        Effect.map((source) => ({
          path: path.relative(DEFAULT_REPO_ROOT, file).replaceAll("\\", "/"),
          source,
        })),
      ),
    ),
  );
  const result = yield* checkCssMotion({
    directory: path.join(DEFAULT_REPO_ROOT, "oxlint-plugin-t3code/exceptions"),
    sources,
  });
  yield* Console.log(result.report);
  if (result.exitCode !== 0) {
    yield* Effect.sync(() => {
      process.exitCode = result.exitCode;
    });
  }
});

export const checkCssMotionCommand = Command.make("check-css-motion", {}, runCssMotionCheck).pipe(
  Command.withDescription(
    "Require infinite CSS animation uses to resolve to slow, capped stepped keyframes.",
  ),
);

if (import.meta.main) {
  Command.run(checkCssMotionCommand, { version: "0.0.0" }).pipe(
    Effect.provide(NodeServices.layer),
    NodeRuntime.runMain,
  );
}
