import * as NodeServices from "@effect/platform-node/NodeServices";
import { assert, describe, it } from "@effect/vitest";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import * as Schema from "effect/Schema";

import { CSS_KIND, type ExceptionEntry } from "@t3tools/oxlint-plugin-t3code/exceptions";

import { checkCssTokens, reconcileCssTokenFindings, scanCssSource } from "./check-css-tokens.ts";

const scan = (source: string) => scanCssSource({ path: "apps/web/src/fixture.css", source });
const encodeUnknownJson = Schema.encodeUnknownSync(Schema.fromJsonString(Schema.Unknown));

describe("CSS token scanning", () => {
  it("exempts theme-source custom properties", () => {
    const source = `
      :root { --color-x: #fff; }
      @layer base { :root { --stage-x: oklch(0.5 0.1 200); } }
      html[data-theme-id="x"] { --app-theme-x: #fff; }
      :is(html[data-theme-id="a"], html[data-theme-id="b"]) { --pair: #fff; }
      @theme { --framework-x: rgb(0 0 0); }
      @layer theme { .scope { --mobile-x: hsl(0 0% 0%); } }
    `;

    assert.deepStrictEqual(scan(source), []);
  });

  it("fingerprints ad-hoc declarations with their selector", () => {
    assert.deepStrictEqual(scan(`.card { background: rgb(0 0 0 / 5%); }`), [
      {
        path: "apps/web/src/fixture.css",
        kind: CSS_KIND,
        fingerprint: ".card{background:rgb(0 0 0 / 5%)}",
      },
    ]);
  });

  it("does not treat color-space names in color-mix as literals", () => {
    assert.deepStrictEqual(scan(`.card { color: color-mix(in oklch, var(--x) 80%, black); }`), []);
  });

  it("finds custom properties outside palette ancestors", () => {
    assert.deepStrictEqual(scan(`@utility x { --y: #000; }`), [
      {
        path: "apps/web/src/fixture.css",
        kind: CSS_KIND,
        fingerprint: "@utility x{--y:#000}",
      },
    ]);
  });

  it("keeps the ancestor stack aligned across an empty block header", () => {
    assert.deepStrictEqual(scan(`.outer { { } .card { color: #fff; } }`), [
      {
        path: "apps/web/src/fixture.css",
        kind: CSS_KIND,
        fingerprint: ".outer > .card{color:#fff}",
      },
    ]);
  });

  it("does not exempt a descendant selector that merely contains a theme-id block", () => {
    assert.deepStrictEqual(scan(`html[data-theme-id="x"] .card { --composer-glass: #fff; }`), [
      {
        path: "apps/web/src/fixture.css",
        kind: CSS_KIND,
        fingerprint: 'html[data-theme-id="x"] .card{--composer-glass:#fff}',
      },
    ]);
  });

  it("does not exempt negated root selectors", () => {
    assert.deepStrictEqual(scan(`body:not(:root) { --x: #fff; }`), [
      {
        path: "apps/web/src/fixture.css",
        kind: CSS_KIND,
        fingerprint: "body:not(:root){--x:#fff}",
      },
    ]);
  });

  it("excludes URL fragments before matching raw colours", () => {
    assert.deepStrictEqual(scan(`.icon { mask: url(#abcdef); }`), []);
  });

  it("skips generated files by their first line", () => {
    assert.deepStrictEqual(
      scan(`/* Generated by scripts/example.ts. Do not edit manually. */\n.x { color: #fff; }`),
      [],
    );
  });
});

it.layer(NodeServices.layer)("CSS ledger reconciliation", (it) => {
  it.effect("skips a dangling CSS symlink with a warning", () =>
    Effect.scoped(
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const repoRoot = yield* fs.makeTempDirectoryScoped({ prefix: "css-token-walk-" });
        const sourceDirectory = path.join(repoRoot, "apps/web/src/nested");
        yield* fs.makeDirectory(sourceDirectory, { recursive: true });
        yield* fs.symlink(
          path.join(repoRoot, "missing.css"),
          path.join(sourceDirectory, "dangling.css"),
        );

        const warnings: Array<string> = [];
        const result = yield* checkCssTokens({
          cwd: repoRoot,
          directory: path.join(repoRoot, "exceptions"),
          warn: (warning) => warnings.push(warning),
        });

        assert.equal(result.exitCode, 0);
        assert.deepStrictEqual(warnings, [
          "CSS source scan: skipped unreadable entry apps/web/src/nested/dangling.css",
        ]);
      }),
    ),
  );

  it.effect("returns a non-zero result naming an unlisted finding", () =>
    Effect.scoped(
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const directory = yield* fs.makeTempDirectoryScoped({ prefix: "css-token-ledger-" });
        const ledgered = scan(`.one { color: #fff; }`)[0]!;
        const unlisted = scan(`.two { background: rgb(0 0 0); }`)[0]!;
        const entry: ExceptionEntry = {
          ...ledgered,
          owner: "karel",
          reason: "fixture exception",
          expires: "never",
        };
        yield* fs.writeFileString(
          path.join(directory, "no-theme-escape-hatches.json"),
          `${encodeUnknownJson([entry])}\n`,
        );

        const result = reconcileCssTokenFindings({
          directory,
          findings: [ledgered, unlisted],
        });

        assert.equal(result.exitCode, 1);
        assert.equal(result.problemCount, 1);
        assert.include(result.report, "unlisted apps/web/src/fixture.css:css-declaration");
        assert.include(result.report, unlisted.fingerprint);
      }),
    ),
  );
});
