import * as NodeServices from "@effect/platform-node/NodeServices";
import { assert, it } from "@effect/vitest";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import * as Stream from "effect/Stream";
import { ChildProcess, ChildProcessSpawner } from "effect/unstable/process";

import { collectCssSources } from "./cssSources.ts";

const collectStreamAsString = <E>(stream: Stream.Stream<Uint8Array, E>): Effect.Effect<string, E> =>
  stream.pipe(
    Stream.decodeText(),
    Stream.runFold(
      () => "",
      (acc, chunk) => acc + chunk,
    ),
  );

const runGit = Effect.fn("test.runCssSourceGit")(function* (
  cwd: string,
  args: ReadonlyArray<string>,
) {
  const spawner = yield* ChildProcessSpawner.ChildProcessSpawner;
  const child = yield* spawner.spawn(ChildProcess.make("git", args, { cwd }));
  const [stdout, stderr, exitCode] = yield* Effect.all(
    [
      collectStreamAsString(child.stdout),
      collectStreamAsString(child.stderr),
      child.exitCode.pipe(Effect.map(Number)),
    ],
    { concurrency: "unbounded" },
  );
  if (exitCode !== 0) {
    return yield* Effect.die(
      new Error(`test fixture git ${args.join(" ")} exited ${exitCode}: ${stderr || stdout}`),
    );
  }
});

it.layer(NodeServices.layer)("CSS source collection", (it) => {
  it.effect("falls back to an excluded, generated, and unreadable-safe directory walk", () =>
    Effect.scoped(
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const repoRoot = yield* fs.makeTempDirectoryScoped({ prefix: "css-sources-walk-" });
        const includedPath = path.join(repoRoot, "apps/web/src/included.css");
        const generatedPath = path.join(repoRoot, "apps/web/src/generated.css");
        const excludedPath = path.join(repoRoot, "apps/mobile/build/excluded.css");
        const excludedNestedDanglingPath = path.join(repoRoot, "apps/mobile/build/dangling.css");
        const excludedDanglingPath = path.join(repoRoot, "apps/mobile/ios");
        const danglingPath = path.join(repoRoot, "apps/mobile/source/dangling.css");

        yield* fs.makeDirectory(path.dirname(includedPath), { recursive: true });
        yield* fs.makeDirectory(path.dirname(excludedPath), { recursive: true });
        yield* fs.makeDirectory(path.dirname(danglingPath), { recursive: true });
        yield* fs.writeFileString(includedPath, ".included { color: currentColor; }\n");
        yield* fs.writeFileString(
          generatedPath,
          "/* Generated by scripts/fixture.ts. Do not edit manually. */\n.generated {}\n",
        );
        yield* fs.writeFileString(excludedPath, ".excluded {}\n");
        yield* fs.symlink(path.join(repoRoot, "missing-build.css"), excludedNestedDanglingPath);
        yield* fs.symlink(path.join(repoRoot, "missing-ios"), excludedDanglingPath);
        yield* fs.symlink(path.join(repoRoot, "missing.css"), danglingPath);

        const warnings: Array<string> = [];
        const sources = yield* collectCssSources({
          repoRoot,
          warn: (warning) => warnings.push(warning),
        });

        assert.deepStrictEqual(sources, [
          {
            path: "apps/web/src/included.css",
            source: ".included { color: currentColor; }\n",
          },
        ]);
        assert.deepStrictEqual(warnings, [
          "CSS source scan: skipped unreadable entry apps/mobile/source/dangling.css",
        ]);
      }),
    ),
  );

  it.effect("uses tracked and untracked non-ignored CSS inside a git checkout", () =>
    Effect.scoped(
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const repoRoot = yield* fs.makeTempDirectoryScoped({ prefix: "css-sources-git-" });
        const trackedPath = path.join(repoRoot, "apps/web/src/tracked.css");
        const excludedPath = path.join(repoRoot, "apps/mobile/ios/excluded.css");
        const trackedDanglingPath = path.join(repoRoot, "apps/mobile/tracked-dangling.css");
        const untrackedPath = path.join(repoRoot, "apps/web/src/untracked.css");
        const ignoredPath = path.join(repoRoot, "apps/web/src/ignored.css");

        yield* runGit(repoRoot, ["init", "-q"]);
        yield* fs.makeDirectory(path.dirname(trackedPath), { recursive: true });
        yield* fs.makeDirectory(path.dirname(excludedPath), { recursive: true });
        yield* fs.writeFileString(trackedPath, ".tracked {}\n");
        yield* fs.writeFileString(excludedPath, ".excluded {}\n");
        yield* fs.symlink(path.join(repoRoot, "missing.css"), trackedDanglingPath);
        yield* fs.writeFileString(path.join(repoRoot, ".gitignore"), "apps/web/src/ignored.css\n");
        yield* runGit(repoRoot, ["add", "-A"]);
        yield* fs.writeFileString(untrackedPath, ".untracked {}\n");
        yield* fs.writeFileString(ignoredPath, ".ignored {}\n");

        const warnings: Array<string> = [];
        const sources = yield* collectCssSources({
          repoRoot,
          warn: (warning) => warnings.push(warning),
        });

        assert.deepStrictEqual(sources, [
          { path: "apps/web/src/tracked.css", source: ".tracked {}\n" },
          { path: "apps/web/src/untracked.css", source: ".untracked {}\n" },
        ]);
        assert.deepStrictEqual(warnings, [
          "CSS source scan: skipped unreadable entry apps/mobile/tracked-dangling.css",
        ]);
      }),
    ),
  );
});
