import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";
import * as Path from "effect/Path";
import * as PlatformError from "effect/PlatformError";
import { ChildProcess, ChildProcessSpawner } from "effect/unstable/process";
import * as NodeProcess from "node:process";

const CSS_SOURCE_ROOTS = ["apps/web/src", "apps/mobile"] as const;
const EXCLUDED_DIRECTORY_NAMES = new Set([
  "node_modules",
  "dist",
  "dist-electron",
  ".repos",
  "ios",
  "android",
  "build",
  ".expo",
  "Pods",
  "DerivedData",
]);
const GENERATED_HEADER_PATTERN =
  /^\s*\/\*[\s\S]{0,240}?generated by [\s\S]*?do not edit manually\.[\s\S]*?\*\//iu;

export interface CssSource {
  readonly path: string;
  readonly source: string;
}

export interface CollectCssSourcesOptions {
  readonly repoRoot: string;
  readonly warn?: (warning: string) => void;
}

const normalizePath = (filePath: string): string => filePath.replaceAll("\\", "/");

const isExcludedDirectoryName = (name: string): boolean =>
  name.startsWith(".") || EXCLUDED_DIRECTORY_NAMES.has(name);

const hasExcludedDirectory = (filePath: string): boolean =>
  normalizePath(filePath).split("/").slice(0, -1).some(isExcludedDirectoryName);

const isInCssSourceRoot = (filePath: string): boolean => {
  const normalizedPath = normalizePath(filePath);
  return CSS_SOURCE_ROOTS.some((root) => normalizedPath.startsWith(`${root}/`));
};

const listGitCssFiles = (
  repoRoot: string,
): Effect.Effect<
  ReadonlyArray<string> | undefined,
  PlatformError.PlatformError,
  ChildProcessSpawner.ChildProcessSpawner
> =>
  Effect.gen(function* () {
    const spawner = yield* ChildProcessSpawner.ChildProcessSpawner;
    const isCheckout = yield* spawner.exitCode(
      ChildProcess.make("git", ["rev-parse", "--is-inside-work-tree"], { cwd: repoRoot }),
    );
    if (Number(isCheckout) !== 0) return undefined;

    const stdout = yield* spawner.string(
      ChildProcess.make(
        "git",
        ["ls-files", "-z", "--cached", "--others", "--exclude-standard", "--", "*.css"],
        { cwd: repoRoot },
      ),
    );
    return stdout
      .split("\0")
      .filter((filePath) => filePath.length > 0)
      .map(normalizePath)
      .filter((filePath) => isInCssSourceRoot(filePath) && !hasExcludedDirectory(filePath));
  });

const warnUnreadable = (filePath: string, warn: (warning: string) => void): Effect.Effect<void> =>
  Effect.sync(() => warn(`CSS source scan: skipped unreadable entry ${normalizePath(filePath)}`));

const statOrSkip = (
  absolutePath: string,
  relativePath: string,
  warn: (warning: string) => void,
): Effect.Effect<FileSystem.File.Info | undefined, never, FileSystem.FileSystem> =>
  Effect.service(FileSystem.FileSystem).pipe(
    Effect.flatMap((fs) => fs.stat(absolutePath)),
    Effect.catch(() => warnUnreadable(relativePath, warn).pipe(Effect.as(undefined))),
  );

function walkCssFiles(
  repoRoot: string,
  relativeDirectory: string,
  warn: (warning: string) => void,
): Effect.Effect<ReadonlyArray<string>, never, FileSystem.FileSystem | Path.Path> {
  return Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const absoluteDirectory = path.join(repoRoot, relativeDirectory);
    const exists = yield* fs
      .exists(absoluteDirectory)
      .pipe(Effect.catch(() => warnUnreadable(relativeDirectory, warn).pipe(Effect.as(false))));
    if (!exists) return [];

    const entries = yield* fs
      .readDirectory(absoluteDirectory)
      .pipe(Effect.catch(() => warnUnreadable(relativeDirectory, warn).pipe(Effect.as(undefined))));
    if (entries === undefined) return [];

    const files: Array<string> = [];
    for (const entry of entries) {
      if (isExcludedDirectoryName(entry)) continue;
      const relativePath = normalizePath(path.join(relativeDirectory, entry));
      const absolutePath = path.join(repoRoot, relativePath);
      const stat = yield* statOrSkip(absolutePath, relativePath, warn);
      if (stat === undefined) continue;
      if (stat.type === "Directory") {
        files.push(...(yield* walkCssFiles(repoRoot, relativePath, warn)));
      } else if (stat.type === "File" && path.extname(entry) === ".css") {
        files.push(relativePath);
      }
    }
    return files;
  });
}

/** Matches the generated-file header shared by every CSS scanner. */
export const isGeneratedCssSource = (source: string): boolean =>
  GENERATED_HEADER_PATTERN.test(source.slice(0, 512));

/** Collects authored CSS from Git-visible source, with an excluded-directory fallback outside Git. */
export const collectCssSources = Effect.fn("collectCssSources")(function* ({
  repoRoot,
  warn = (warning) => {
    NodeProcess.stderr.write(`${warning}\n`);
  },
}: CollectCssSourcesOptions) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const gitFiles = yield* listGitCssFiles(repoRoot).pipe(Effect.orElseSucceed(() => undefined));
  const files = (
    gitFiles ??
    (yield* Effect.all(CSS_SOURCE_ROOTS.map((root) => walkCssFiles(repoRoot, root, warn)))).flat()
  ).toSorted();
  const sources: Array<CssSource> = [];

  for (const relativePath of files) {
    const absolutePath = path.join(repoRoot, relativePath);
    const stat = yield* statOrSkip(absolutePath, relativePath, warn);
    if (stat?.type !== "File") continue;
    const source = yield* fs
      .readFileString(absolutePath)
      .pipe(Effect.catch(() => warnUnreadable(relativePath, warn).pipe(Effect.as(undefined))));
    if (source !== undefined && !isGeneratedCssSource(source)) {
      sources.push({ path: relativePath, source });
    }
  }

  return sources;
});
